/*
 * Params.cpp
 *
 *  Created on: Feb 2, 2018
 *      Author: boz
 */

#include "Params.h"

std::string CAMERA_IMAGE_TOPIC_1;

std::string CAMERA_IMAGE_TOPIC_2;

std::string CAMERA_IMAGE_TOPIC_3;

std::string CAMERA_IMAGE_TOPIC_4;

int RED_HUE_HSV_HIGH;
int RED_HUE_HSV_LOW;
int RED_SATURATION_HSV_HIGH;
int RED_SATURATION_HSV_LOW;
int RED_VALUE_HSV_HIGH;
int RED_VALUE_HSV_LOW;

int GREEN_HUE_HSV_HIGH;
int GREEN_HUE_HSV_LOW;
int GREEN_SATURATION_HSV_HIGH;
int GREEN_SATURATION_HSV_LOW;
int GREEN_VALUE_HSV_HIGH;
int GREEN VALUE_HSV_LOW;




